<?php
namespace App\Http\Controllers\Site;

use Illuminate\Console\Command;

class cronTaskCheckOfflineUsers extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'checkOfflineUsers:init';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Start game Gwent server';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    public function error($string, $verbosity = null)
    {
        parent::error($string, $verbosity); // TODO: Change the autogenerated stub
    }
    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function checkOfflineUsers(){
        /*Every 4 minutes*/
        /*Online counters*/
        $date = date('Y-m-d H:i:s', time()-240);
        $users_offline = \DB::table('users')->select('id','user_online','updated_at')
            ->where('user_online','>',0)
            ->where('updated_at','<',$date)
            ->update(['user_online' => 0]);
    }
}